### PR TITLE
DM-5466: obs_decam calibration ingest uses fragile relative paths

### PR DESCRIPTION
**Pull request by mrawls**

### CODE REVIEW

**Comment by mrawls** [comment]
One thing I would like to add to this repo's README is a short list of the commands used on the command line to ingest all of the data in this testdata directory structure. I think this would be very instructive for future users. Currently, there are generic examples for ingesting raw images and defects in the obs_decam README. If @hsinfang could please help me construct similar example commands with the exact directory structure used here, I would be happy to add them to this repo's README.

**Comment by hsinfang** [comment]
I tested the following steps with the current master and it seems to generate the same calibRegistry.sqlite3 as in the master and passes `obs_decam` tests: 
```
ingestCalibs.py ../../rawData --calib . masterCal/*fits --validity 999
ingestCalibs.py ../../rawData --calib . FRINGE/2013-11-15/z/FRINGE-2013-11-15-01.fits --validity 999
ingestCalibs.py ../../rawData --calib . --calibType defect bpm/2013-07-16/*fits --validity 0
```
[Edit: seems that I really have to run this at `rawData/cpCalib`... :( ]

**Comment by hsinfang** [comment]
p.s. The above steps are the same as suggested by `obs_decam` README.md Line 64 (current master).  If they change we should update `obs_decam` README.md as well.

**Review by hsinfang — APPROVED** [review]
Please squash the commits

**Pull request merged**
