### PR TITLE
Add linearization lookup tables

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by RobertLuptonTheGood** [comment]
Why are the linearisation tables in the test product, not in obs_decam?

**Comment by RobertLuptonTheGood** [comment]
Why are we committing the pickle files rather than having the data to generate the linearisation in git, and having scons build the pickle files?

**Comment by r-owen** [comment]
The linearization tables are calibration products, so they live with the other calibration products. That explains why they are in the test product and why scons does not build them.

Note that obs_subaru is different because the amp info catalogs are part of the obs_ package. However, that is something @ktlim would like to change, and I suspect he's right. Amp info tables vary with time and ought to be considered calibration products so we can retrieve the appropriate version based on the time at which the data was taken, and potentially process data taken at different times in the same run.

**Comment by PaulPrice** [comment]
It does mean that every time you create a new data repo, you need to copy the linearization tables from somewhere.  That's very unusual for HSC, but it seems to be common for DECam.  But there needs to be some master source of these linearization tables that people can get them from, and a link in obs_decam that tells people where to get them (or a script that will generate them or download them).

**Comment by r-owen** [comment]
@PaulPrice I agree that the source of all calibration data ought to be properly documented. I think it's out of scope for this ticket, but could well be relevant for DM-6508.

**Comment by ktlim** [comment]
Calibration data repositories (and databases, eventually), like raw data repositories, need to be discoverable, remotely accessible, locally cacheable, and "linked" into the repository tree for any data processing that needs their information.  Most of that is still to be built, unfortunately.  Using git/eups to handle the version axis for {{astrometry_net_data}} didn't work out too well, but it might be better for a putative {{calib_decam}} package.  NateP's upcoming changes to allow the version axis to be handled by a separate Butler dataId don't solve the ultimate question of where the data resides.  (The observation time axis would of course be handled inside the repository as DM-6508 suggests.)

**Comment by RobertLuptonTheGood** [comment]
I am unconvinced by @r-owen 's argument about building the linearisation pickles.   Even if they are calibration products that don't belong in the camera package (and I am unconvinced;  they are very unlikely to evolve with time), we still need a way to version the content and not just commit binaries.

So if test_decam pulls them from somewhere, that somewhere needs to build the pickles from inputs that can be understood and sanely versioned if needs be.

**Pull request closed without merging**
